### ISSUE TITLE
100% coverage displayed in scientific notation

### ISSUE THREAD

**Issue by iwdt** [dewski/vscode-simplecov#10]
I'm not sure if this is incorrect behavior and not feature, but I noticed it and decided to create this issue

## My setup:
Ruby 3.3.4, Simplecov 0.22.0, vscode-simplecov 0.0.5

## Simplecov configuration

```ruby
require 'simplecov'

SimpleCov.start 'rails' do
  enable_coverage :branch
  minimum_coverage_by_file 80

  # Exclude previews from simple cov
  previews = Pathname('app/views').glob('**/*preview.rb').map(&:to_s)
  add_filter previews

  add_group 'Repositories', 'app/repositories'
  add_group 'Interactors', 'app/interactors'
  add_group 'Components', 'app/views/components'
  add_group 'Contracts', ['app/forms', 'app/contracts']
  add_group 'Policies', 'app/policies'
end
```

## Screenshot

<img width="400" alt="image" src="https://github.com/user-attachments/assets/7fb84199-439f-4a5f-8ace-d29f53ae4702">

**Comment by dewski** [comment]
Thank you for reporting and providing a pull request! The updated extension has been published to the VSCode Marketplace.

**Comment by iwdt** [comment]
great, it works!

<img width="300" alt="image" src="https://github.com/user-attachments/assets/f4cf8655-f6a8-482b-a994-bc62e94ce439">
