### ISSUE TITLE
How to turn on/off and re-render highlight?

### ISSUE THREAD

**Issue by amkisko** [dewski/vscode-simplecov#13]
It would be nice to have ability to re-render highlight and calculations, in pair with complete turn on/off of highlight.

At the moment it calls `removeCodeCoverageOnFileSave` whenever there are changes, but no visible option on how to activate it back for non-changed files.

From UX perspective it makes sense to show warning that highlight can't be shown for edited file because `.resultset.json` is older than current file.

**Comment by orangedsoft** [comment]
Did you find a way to toggle the coverage highlighting without having to fully disable the plugin? I would much rather temporarily view coverage when checking than have the files permanently highlighted.

**Comment by amkisko** [comment]
@orangedsoft Hey! Nope, I did not find a way to do so. By looking at the code it requires some work here. At this point I am already quite used to this over illuminated palette, so not yet investing into fixing the extension. :)

**Comment by dewski** [comment]
Thanks for opening the issue @amkisko and sharing feedback. I'll look at adding a keyboard shortcut command that people can bind and report back. The keyboard shortcut would allow you to toggle coverage on a file. I do still like the user experience of on save clearing on editors, otherwise it'd be a bit much permanently highlighting the coverage and being required to use a shortcut to remove it.

**Comment by dewski** [comment]
Version [v0.0.7]() has been published to the VS Code marketplace! You can download it now if your editor hasn't already automatically updated the extension.

The following [commands](https://github.com/dewski/vscode-simplecov?tab=readme-ov-file#commands) were added:

- `simplecov.coverage.toggle`: Toggle the display of code coverage.
- `simplecov.coverage.apply`: Apply the coverage to the currently active file.
- `simplecov.coverage.remove`: Remove the coverage from the currently active file.

They are not bound to any shortcuts by default. To set it up you can follow the [VS Code shortcut editor documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor).

Let me know what you think!
