### ISSUE TITLE
Allow coverage directory to be configured

### ISSUE THREAD

**Issue by nfm** [dewski/vscode-simplecov#6]
Hi @dewski - super excited to see this extension, I've been looking for something like it for ages ❤️ 

It would be cool if it was possible to customize the directory that coverage reports are loaded from. Currently this is hardcoded to `coverage/`: https://github.com/dewski/vscode-simplecov/blob/6fb90bb6e2fff95332e7afbb8b5ed461bfcd763a/src/extension.ts#L449-L450

In our case, we're storing this elsewhere - we generate coverage for both backend and frontend tests and aren't using the Simplecov default `coverage/` location as a result.

If this is something you'd be open to, I can spin up a PR.

**Comment by dewski** [comment]
Appreciate you opening an issue about your use case! Happy to accept a PR for this. Otherwise I am happy to add a setting for it as well.

**Comment by dewski** [comment]
The extension has been updated with this change and published on the marketplace as v0.0.4.

**Comment by nfm** [comment]
Thanks @dewski!
